on:
  pull_request:
    branches:
      - staging
    types: [closed]

jobs:
  pull-request:
    if: (github.head_ref == 'production')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "staging" # If blank, default: triggered branch
          destination_branch: "master" # If blank, default: master
          pr_title: "Sync ${{ github.ref }} into master" # Title of pull request
          pr_body: ":crown: *An automated PR*" # Full markdown support, requires pr_title to be set
          pr_template: ".github/AUTO_PULL_REQUEST_TEMPLATE.md" # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: "" # Comma-separated list (no spaces)
          pr_assignee: "" # Comma-separated list (no spaces)
          pr_label: "" # Comma-separated list (no spaces)
          pr_milestone: "" # Milestone name
          pr_draft: false # Creates pull request as draft
          pr_allow_empty: true # Creates pull request even if there are no changes
          github_token: ${{ secrets.GH_TOKEN }}
